// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xoojwxdqnfhwnneexope.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhvb2p3eGRxbmZod25uZWV4b3BlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2Nzc0MjMsImV4cCI6MjA1OTI1MzQyM30.HSdOQg7oTHWUEjv3lX56NBLJdplErJ5hOhVeAOejR5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);